extends:
    eslint:recommended
env:
    es6: true,
    browser: true
    node: true
parser:
    babel-eslint
parserOptions:
    sourceType: module
    ecmaFeatures:
        modules: true
rules:
    comma-dangle: ['error', 'only-multiline']
    no-cond-assign: 2
    no-dupe-args: 2
    no-dupe-keys: 2

    consistent-return: 2
    curly: ['error', 'multi-or-nest']
    dot-location: 2
    no-alert: 2
    eqeqeq: 2
    no-eval: 2
    no-else-return: 2
    no-fallthrough: 2

    no-console: 0
